#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu
# machine to respect above requirements

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html
