#!/usr/bin/env bash
# write a Bash script that configures a new

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
