#!/usr/bin/env bash
#When passed the argument `start`:
#1. Starts manage_my_process
#2. Creates a file containings its PID in /var/run/my_process.pid
#3. Displays "manage_my_process started"
#When passed the argument `stop`:
#1. Stops manage_my_process
#2. Deletes the file /var/run/my_process.pid
#3. Displays "manage_my_process stopped"
#When passed the argument `restart`:
#1. Stops manage_my_process
#2. Deletes the file /var/run/my_process.pid
#3. Starts manage_my_process
#4. Creates a file containing its PID in /var/run/my_process.pid
#5. Displays "manage_my_process restarted"

case $1 in
    "start")
	./manage_my_process & > /var/run/my_process.pid
	echo 'manage_my_process started';;
    "restart")
	id=$(cat /var/run/my_process.pid)
	kill -s SIGSTOP "$id"
	rm /var/run/my_process.pid
	./manage_my_process & > /var/run/my_process.pid
	echo 'manage_my_process restarted';;
    "stop")
	id=$(cat /var/run/my_process.pid)
	kill -s SIGSTOP "$id"
	rm /var/run/my_process.pid
	echo 'manage_my_process stopped';;
    *)
	echo 'Usage: manage_my_process {start|stop|restart}';;
esac
